/* Automatically generated by wasm2c */
#ifndef MATRIX_H_GENERATED_
#define MATRIX_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
extern wasm_rt_memory_t* w2c_env_memory(struct w2c_env*);

typedef struct w2c_matrix {
  struct w2c_env* w2c_env_instance;
  /* import: 'env' 'memory' */
  wasm_rt_memory_t *w2c_env_memory;
  u32 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  u32 w2c_g3;
  u32 w2c_g4;
} w2c_matrix;

void wasm2c_matrix_instantiate(w2c_matrix*, struct w2c_env*);
void wasm2c_matrix_free(w2c_matrix*);
wasm_rt_func_type_t wasm2c_matrix_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' 'rand' */
u32 w2c_env_rand(struct w2c_env*);

extern const u64 wasm2c_matrix_min_env_memory;
extern const u64 wasm2c_matrix_max_env_memory;
extern const u8 wasm2c_matrix_is64_env_memory;

/* export: 'performance_test' */
void w2c_matrix_performance_test(w2c_matrix*);

#ifdef __cplusplus
}
#endif

#endif  /* MATRIX_H_GENERATED_ */
