/* Automatically generated by wasm2c */
#ifndef ECHO_H_GENERATED_
#define ECHO_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_wasi__unstable;

typedef struct w2c_echo {
  struct w2c_wasi__unstable* w2c_wasi__unstable_instance;
  u32 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  u32 w2c_g3;
  u32 w2c_g4;
  u32 w2c_g5;
  wasm_rt_memory_t w2c_memory;
} w2c_echo;

void wasm2c_echo_instantiate(w2c_echo*, struct w2c_wasi__unstable*);
void wasm2c_echo_free(w2c_echo*);
wasm_rt_func_type_t wasm2c_echo_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'wasi_unstable' 'args_get' */
u32 w2c_wasi__unstable_args_get(struct w2c_wasi__unstable*, u32, u32);

/* import: 'wasi_unstable' 'args_sizes_get' */
u32 w2c_wasi__unstable_args_sizes_get(struct w2c_wasi__unstable*, u32, u32);

/* import: 'wasi_unstable' 'fd_write' */
u32 w2c_wasi__unstable_fd_write(struct w2c_wasi__unstable*, u32, u32, u32, u32);

/* import: 'wasi_unstable' 'proc_exit' */
void w2c_wasi__unstable_proc_exit(struct w2c_wasi__unstable*, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_echo_memory(w2c_echo* instance);

/* export: '_start' */
void w2c_echo_0x5Fstart(w2c_echo*);

#ifdef __cplusplus
}
#endif

#endif  /* ECHO_H_GENERATED_ */
