/* Automatically generated by wasm2c */
#ifndef ADDRESS_H_GENERATED_
#define ADDRESS_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_address {
  wasm_rt_memory_t w2c_M0;
} w2c_address;

void wasm2c_address_instantiate(w2c_address*);
void wasm2c_address_free(w2c_address*);
wasm_rt_func_type_t wasm2c_address_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: '8u_good1' */
u32 w2c_address_8u_good1(w2c_address*, u32);

/* export: '8u_good2' */
u32 w2c_address_8u_good2(w2c_address*, u32);

/* export: '8u_good3' */
u32 w2c_address_8u_good3(w2c_address*, u32);

/* export: '8u_good4' */
u32 w2c_address_8u_good4(w2c_address*, u32);

/* export: '8u_good5' */
u32 w2c_address_8u_good5(w2c_address*, u32);

/* export: '8s_good1' */
u32 w2c_address_8s_good1(w2c_address*, u32);

/* export: '8s_good2' */
u32 w2c_address_8s_good2(w2c_address*, u32);

/* export: '8s_good3' */
u32 w2c_address_8s_good3(w2c_address*, u32);

/* export: '8s_good4' */
u32 w2c_address_8s_good4(w2c_address*, u32);

/* export: '8s_good5' */
u32 w2c_address_8s_good5(w2c_address*, u32);

/* export: '16u_good1' */
u32 w2c_address_16u_good1(w2c_address*, u32);

/* export: '16u_good2' */
u32 w2c_address_16u_good2(w2c_address*, u32);

/* export: '16u_good3' */
u32 w2c_address_16u_good3(w2c_address*, u32);

/* export: '16u_good4' */
u32 w2c_address_16u_good4(w2c_address*, u32);

/* export: '16u_good5' */
u32 w2c_address_16u_good5(w2c_address*, u32);

/* export: '16s_good1' */
u32 w2c_address_16s_good1(w2c_address*, u32);

/* export: '16s_good2' */
u32 w2c_address_16s_good2(w2c_address*, u32);

/* export: '16s_good3' */
u32 w2c_address_16s_good3(w2c_address*, u32);

/* export: '16s_good4' */
u32 w2c_address_16s_good4(w2c_address*, u32);

/* export: '16s_good5' */
u32 w2c_address_16s_good5(w2c_address*, u32);

/* export: '32_good1' */
u32 w2c_address_32_good1(w2c_address*, u32);

/* export: '32_good2' */
u32 w2c_address_32_good2(w2c_address*, u32);

/* export: '32_good3' */
u32 w2c_address_32_good3(w2c_address*, u32);

/* export: '32_good4' */
u32 w2c_address_32_good4(w2c_address*, u32);

/* export: '32_good5' */
u32 w2c_address_32_good5(w2c_address*, u32);

/* export: '8u_bad' */
void w2c_address_8u_bad(w2c_address*, u32);

/* export: '8s_bad' */
void w2c_address_8s_bad(w2c_address*, u32);

/* export: '16u_bad' */
void w2c_address_16u_bad(w2c_address*, u32);

/* export: '16s_bad' */
void w2c_address_16s_bad(w2c_address*, u32);

/* export: '32_bad' */
void w2c_address_32_bad(w2c_address*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* ADDRESS_H_GENERATED_ */
