/* Automatically generated by wasm2c */
#ifndef BR_IF_H_GENERATED_
#define BR_IF_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_br__if {
  u32 w2c_g0;
  wasm_rt_memory_t w2c_M0;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_br__if;

void wasm2c_br__if_instantiate(w2c_br__if*);
void wasm2c_br__if_free(w2c_br__if*);
wasm_rt_func_type_t wasm2c_br__if_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'type-i32' */
void w2c_br__if_type0x2Di32(w2c_br__if*);

/* export: 'type-i64' */
void w2c_br__if_type0x2Di64(w2c_br__if*);

/* export: 'type-f32' */
void w2c_br__if_type0x2Df32(w2c_br__if*);

/* export: 'type-f64' */
void w2c_br__if_type0x2Df64(w2c_br__if*);

/* export: 'type-i32-value' */
u32 w2c_br__if_type0x2Di320x2Dvalue(w2c_br__if*);

/* export: 'type-i64-value' */
u64 w2c_br__if_type0x2Di640x2Dvalue(w2c_br__if*);

/* export: 'type-f32-value' */
f32 w2c_br__if_type0x2Df320x2Dvalue(w2c_br__if*);

/* export: 'type-f64-value' */
f64 w2c_br__if_type0x2Df640x2Dvalue(w2c_br__if*);

/* export: 'as-block-first' */
u32 w2c_br__if_as0x2Dblock0x2Dfirst(w2c_br__if*, u32);

/* export: 'as-block-mid' */
u32 w2c_br__if_as0x2Dblock0x2Dmid(w2c_br__if*, u32);

/* export: 'as-block-last' */
void w2c_br__if_as0x2Dblock0x2Dlast(w2c_br__if*, u32);

/* export: 'as-block-first-value' */
u32 w2c_br__if_as0x2Dblock0x2Dfirst0x2Dvalue(w2c_br__if*, u32);

/* export: 'as-block-mid-value' */
u32 w2c_br__if_as0x2Dblock0x2Dmid0x2Dvalue(w2c_br__if*, u32);

/* export: 'as-block-last-value' */
u32 w2c_br__if_as0x2Dblock0x2Dlast0x2Dvalue(w2c_br__if*, u32);

/* export: 'as-loop-first' */
u32 w2c_br__if_as0x2Dloop0x2Dfirst(w2c_br__if*, u32);

/* export: 'as-loop-mid' */
u32 w2c_br__if_as0x2Dloop0x2Dmid(w2c_br__if*, u32);

/* export: 'as-loop-last' */
void w2c_br__if_as0x2Dloop0x2Dlast(w2c_br__if*, u32);

/* export: 'as-br-value' */
u32 w2c_br__if_as0x2Dbr0x2Dvalue(w2c_br__if*);

/* export: 'as-br_if-cond' */
void w2c_br__if_as0x2Dbr_if0x2Dcond(w2c_br__if*);

/* export: 'as-br_if-value' */
u32 w2c_br__if_as0x2Dbr_if0x2Dvalue(w2c_br__if*);

/* export: 'as-br_if-value-cond' */
u32 w2c_br__if_as0x2Dbr_if0x2Dvalue0x2Dcond(w2c_br__if*, u32);

/* export: 'as-br_table-index' */
void w2c_br__if_as0x2Dbr_table0x2Dindex(w2c_br__if*);

/* export: 'as-br_table-value' */
u32 w2c_br__if_as0x2Dbr_table0x2Dvalue(w2c_br__if*);

/* export: 'as-br_table-value-index' */
u32 w2c_br__if_as0x2Dbr_table0x2Dvalue0x2Dindex(w2c_br__if*);

/* export: 'as-return-value' */
u64 w2c_br__if_as0x2Dreturn0x2Dvalue(w2c_br__if*);

/* export: 'as-if-cond' */
u32 w2c_br__if_as0x2Dif0x2Dcond(w2c_br__if*, u32);

/* export: 'as-if-then' */
void w2c_br__if_as0x2Dif0x2Dthen(w2c_br__if*, u32, u32);

/* export: 'as-if-else' */
void w2c_br__if_as0x2Dif0x2Delse(w2c_br__if*, u32, u32);

/* export: 'as-select-first' */
u32 w2c_br__if_as0x2Dselect0x2Dfirst(w2c_br__if*, u32);

/* export: 'as-select-second' */
u32 w2c_br__if_as0x2Dselect0x2Dsecond(w2c_br__if*, u32);

/* export: 'as-select-cond' */
u32 w2c_br__if_as0x2Dselect0x2Dcond(w2c_br__if*);

/* export: 'as-call-first' */
u32 w2c_br__if_as0x2Dcall0x2Dfirst(w2c_br__if*);

/* export: 'as-call-mid' */
u32 w2c_br__if_as0x2Dcall0x2Dmid(w2c_br__if*);

/* export: 'as-call-last' */
u32 w2c_br__if_as0x2Dcall0x2Dlast(w2c_br__if*);

/* export: 'as-call_indirect-func' */
u32 w2c_br__if_as0x2Dcall_indirect0x2Dfunc(w2c_br__if*);

/* export: 'as-call_indirect-first' */
u32 w2c_br__if_as0x2Dcall_indirect0x2Dfirst(w2c_br__if*);

/* export: 'as-call_indirect-mid' */
u32 w2c_br__if_as0x2Dcall_indirect0x2Dmid(w2c_br__if*);

/* export: 'as-call_indirect-last' */
u32 w2c_br__if_as0x2Dcall_indirect0x2Dlast(w2c_br__if*);

/* export: 'as-local.set-value' */
u32 w2c_br__if_as0x2Dlocal0x2Eset0x2Dvalue(w2c_br__if*, u32);

/* export: 'as-local.tee-value' */
u32 w2c_br__if_as0x2Dlocal0x2Etee0x2Dvalue(w2c_br__if*, u32);

/* export: 'as-global.set-value' */
u32 w2c_br__if_as0x2Dglobal0x2Eset0x2Dvalue(w2c_br__if*, u32);

/* export: 'as-load-address' */
u32 w2c_br__if_as0x2Dload0x2Daddress(w2c_br__if*);

/* export: 'as-loadN-address' */
u32 w2c_br__if_as0x2DloadN0x2Daddress(w2c_br__if*);

/* export: 'as-store-address' */
u32 w2c_br__if_as0x2Dstore0x2Daddress(w2c_br__if*);

/* export: 'as-store-value' */
u32 w2c_br__if_as0x2Dstore0x2Dvalue(w2c_br__if*);

/* export: 'as-storeN-address' */
u32 w2c_br__if_as0x2DstoreN0x2Daddress(w2c_br__if*);

/* export: 'as-storeN-value' */
u32 w2c_br__if_as0x2DstoreN0x2Dvalue(w2c_br__if*);

/* export: 'as-unary-operand' */
f64 w2c_br__if_as0x2Dunary0x2Doperand(w2c_br__if*);

/* export: 'as-binary-left' */
u32 w2c_br__if_as0x2Dbinary0x2Dleft(w2c_br__if*);

/* export: 'as-binary-right' */
u32 w2c_br__if_as0x2Dbinary0x2Dright(w2c_br__if*);

/* export: 'as-test-operand' */
u32 w2c_br__if_as0x2Dtest0x2Doperand(w2c_br__if*);

/* export: 'as-compare-left' */
u32 w2c_br__if_as0x2Dcompare0x2Dleft(w2c_br__if*);

/* export: 'as-compare-right' */
u32 w2c_br__if_as0x2Dcompare0x2Dright(w2c_br__if*);

/* export: 'as-memory.grow-size' */
u32 w2c_br__if_as0x2Dmemory0x2Egrow0x2Dsize(w2c_br__if*);

/* export: 'nested-block-value' */
u32 w2c_br__if_nested0x2Dblock0x2Dvalue(w2c_br__if*, u32);

/* export: 'nested-br-value' */
u32 w2c_br__if_nested0x2Dbr0x2Dvalue(w2c_br__if*, u32);

/* export: 'nested-br_if-value' */
u32 w2c_br__if_nested0x2Dbr_if0x2Dvalue(w2c_br__if*, u32);

/* export: 'nested-br_if-value-cond' */
u32 w2c_br__if_nested0x2Dbr_if0x2Dvalue0x2Dcond(w2c_br__if*, u32);

/* export: 'nested-br_table-value' */
u32 w2c_br__if_nested0x2Dbr_table0x2Dvalue(w2c_br__if*, u32);

/* export: 'nested-br_table-value-index' */
u32 w2c_br__if_nested0x2Dbr_table0x2Dvalue0x2Dindex(w2c_br__if*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* BR_IF_H_GENERATED_ */
