/* Automatically generated by wasm2c */
#ifndef CALL_H_GENERATED_
#define CALL_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_call {
  u32 w2c_g0;
  wasm_rt_memory_t w2c_M0;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_call;

void wasm2c_call_instantiate(w2c_call*);
void wasm2c_call_free(w2c_call*);
wasm_rt_func_type_t wasm2c_call_get_func_type(uint32_t param_count, uint32_t result_count, ...);

#ifndef wasm_multi_ij
#define wasm_multi_ij wasm_multi_ij
struct wasm_multi_ij {
  u32 i0;
  u64 j1;
};
#endif  /* wasm_multi_ij */

#ifndef wasm_multi_id
#define wasm_multi_id wasm_multi_id
struct wasm_multi_id {
  u32 i0;
  f64 d1;
};
#endif  /* wasm_multi_id */

#ifndef wasm_multi_ii
#define wasm_multi_ii wasm_multi_ii
struct wasm_multi_ii {
  u32 i0;
  u32 i1;
};
#endif  /* wasm_multi_ii */

#ifndef wasm_multi_df
#define wasm_multi_df wasm_multi_df
struct wasm_multi_df {
  f64 d0;
  f32 f1;
};
#endif  /* wasm_multi_df */

/* export: 'type-i32' */
u32 w2c_call_type0x2Di32(w2c_call*);

/* export: 'type-i64' */
u64 w2c_call_type0x2Di64(w2c_call*);

/* export: 'type-f32' */
f32 w2c_call_type0x2Df32(w2c_call*);

/* export: 'type-f64' */
f64 w2c_call_type0x2Df64(w2c_call*);

/* export: 'type-i32-i64' */
struct wasm_multi_ij w2c_call_type0x2Di320x2Di64(w2c_call*);

/* export: 'type-first-i32' */
u32 w2c_call_type0x2Dfirst0x2Di32(w2c_call*);

/* export: 'type-first-i64' */
u64 w2c_call_type0x2Dfirst0x2Di64(w2c_call*);

/* export: 'type-first-f32' */
f32 w2c_call_type0x2Dfirst0x2Df32(w2c_call*);

/* export: 'type-first-f64' */
f64 w2c_call_type0x2Dfirst0x2Df64(w2c_call*);

/* export: 'type-second-i32' */
u32 w2c_call_type0x2Dsecond0x2Di32(w2c_call*);

/* export: 'type-second-i64' */
u64 w2c_call_type0x2Dsecond0x2Di64(w2c_call*);

/* export: 'type-second-f32' */
f32 w2c_call_type0x2Dsecond0x2Df32(w2c_call*);

/* export: 'type-second-f64' */
f64 w2c_call_type0x2Dsecond0x2Df64(w2c_call*);

/* export: 'type-all-i32-f64' */
struct wasm_multi_id w2c_call_type0x2Dall0x2Di320x2Df64(w2c_call*);

/* export: 'type-all-i32-i32' */
struct wasm_multi_ii w2c_call_type0x2Dall0x2Di320x2Di32(w2c_call*);

/* export: 'type-all-f32-f64' */
struct wasm_multi_df w2c_call_type0x2Dall0x2Df320x2Df64(w2c_call*);

/* export: 'type-all-f64-i32' */
struct wasm_multi_id w2c_call_type0x2Dall0x2Df640x2Di32(w2c_call*);

/* export: 'as-binary-all-operands' */
u32 w2c_call_as0x2Dbinary0x2Dall0x2Doperands(w2c_call*);

/* export: 'as-mixed-operands' */
u32 w2c_call_as0x2Dmixed0x2Doperands(w2c_call*);

/* export: 'as-call-all-operands' */
struct wasm_multi_ii w2c_call_as0x2Dcall0x2Dall0x2Doperands(w2c_call*);

/* export: 'fac' */
u64 w2c_call_fac(w2c_call*, u64);

/* export: 'fac-acc' */
u64 w2c_call_fac0x2Dacc(w2c_call*, u64, u64);

/* export: 'fib' */
u64 w2c_call_fib(w2c_call*, u64);

/* export: 'even' */
u32 w2c_call_even(w2c_call*, u64);

/* export: 'odd' */
u32 w2c_call_odd(w2c_call*, u64);

/* export: 'runaway' */
void w2c_call_runaway(w2c_call*);

/* export: 'mutual-runaway' */
void w2c_call_mutual0x2Drunaway(w2c_call*);

/* export: 'as-select-first' */
u32 w2c_call_as0x2Dselect0x2Dfirst(w2c_call*);

/* export: 'as-select-mid' */
u32 w2c_call_as0x2Dselect0x2Dmid(w2c_call*);

/* export: 'as-select-last' */
u32 w2c_call_as0x2Dselect0x2Dlast(w2c_call*);

/* export: 'as-if-condition' */
u32 w2c_call_as0x2Dif0x2Dcondition(w2c_call*);

/* export: 'as-br_if-first' */
u32 w2c_call_as0x2Dbr_if0x2Dfirst(w2c_call*);

/* export: 'as-br_if-last' */
u32 w2c_call_as0x2Dbr_if0x2Dlast(w2c_call*);

/* export: 'as-br_table-first' */
u32 w2c_call_as0x2Dbr_table0x2Dfirst(w2c_call*);

/* export: 'as-br_table-last' */
u32 w2c_call_as0x2Dbr_table0x2Dlast(w2c_call*);

/* export: 'as-call_indirect-first' */
u32 w2c_call_as0x2Dcall_indirect0x2Dfirst(w2c_call*);

/* export: 'as-call_indirect-mid' */
u32 w2c_call_as0x2Dcall_indirect0x2Dmid(w2c_call*);

/* export: 'as-call_indirect-last' */
u32 w2c_call_as0x2Dcall_indirect0x2Dlast(w2c_call*);

/* export: 'as-store-first' */
void w2c_call_as0x2Dstore0x2Dfirst(w2c_call*);

/* export: 'as-store-last' */
void w2c_call_as0x2Dstore0x2Dlast(w2c_call*);

/* export: 'as-memory.grow-value' */
u32 w2c_call_as0x2Dmemory0x2Egrow0x2Dvalue(w2c_call*);

/* export: 'as-return-value' */
u32 w2c_call_as0x2Dreturn0x2Dvalue(w2c_call*);

/* export: 'as-drop-operand' */
void w2c_call_as0x2Ddrop0x2Doperand(w2c_call*);

/* export: 'as-br-value' */
u32 w2c_call_as0x2Dbr0x2Dvalue(w2c_call*);

/* export: 'as-local.set-value' */
u32 w2c_call_as0x2Dlocal0x2Eset0x2Dvalue(w2c_call*);

/* export: 'as-local.tee-value' */
u32 w2c_call_as0x2Dlocal0x2Etee0x2Dvalue(w2c_call*);

/* export: 'as-global.set-value' */
u32 w2c_call_as0x2Dglobal0x2Eset0x2Dvalue(w2c_call*);

/* export: 'as-load-operand' */
u32 w2c_call_as0x2Dload0x2Doperand(w2c_call*);

/* export: 'as-unary-operand' */
f32 w2c_call_as0x2Dunary0x2Doperand(w2c_call*);

/* export: 'as-binary-left' */
u32 w2c_call_as0x2Dbinary0x2Dleft(w2c_call*);

/* export: 'as-binary-right' */
u32 w2c_call_as0x2Dbinary0x2Dright(w2c_call*);

/* export: 'as-test-operand' */
u32 w2c_call_as0x2Dtest0x2Doperand(w2c_call*);

/* export: 'as-compare-left' */
u32 w2c_call_as0x2Dcompare0x2Dleft(w2c_call*);

/* export: 'as-compare-right' */
u32 w2c_call_as0x2Dcompare0x2Dright(w2c_call*);

/* export: 'as-convert-operand' */
u64 w2c_call_as0x2Dconvert0x2Doperand(w2c_call*);

/* export: 'return-from-long-argument-list' */
u32 w2c_call_return0x2Dfrom0x2Dlong0x2Dargument0x2Dlist(w2c_call*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* CALL_H_GENERATED_ */
