/* Automatically generated by wasm2c */
#ifndef AUTO_DEBUG_H_GENERATED_
#define AUTO_DEBUG_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_auto__debug {
  u32 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_0x5F_indirect_function_table;
} w2c_auto__debug;

void wasm2c_auto__debug_instantiate(w2c_auto__debug*);
void wasm2c_auto__debug_free(w2c_auto__debug*);
wasm_rt_func_type_t wasm2c_auto__debug_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'memory' */
wasm_rt_memory_t* w2c_auto__debug_memory(w2c_auto__debug* instance);

/* export: 'calculate' */
u32 w2c_auto__debug_calculate(w2c_auto__debug*, u32);

/* export: '__indirect_function_table' */
wasm_rt_funcref_table_t* w2c_auto__debug_0x5F_indirect_function_table(w2c_auto__debug* instance);

/* export: '_initialize' */
void w2c_auto__debug_0x5Finitialize(w2c_auto__debug*);

/* export: 'strerror' */
u32 w2c_auto__debug_strerror(w2c_auto__debug*, u32);

/* export: 'emscripten_stack_init' */
void w2c_auto__debug_emscripten_stack_init(w2c_auto__debug*);

/* export: 'emscripten_stack_get_free' */
u32 w2c_auto__debug_emscripten_stack_get_free(w2c_auto__debug*);

/* export: 'emscripten_stack_get_base' */
u32 w2c_auto__debug_emscripten_stack_get_base(w2c_auto__debug*);

/* export: 'emscripten_stack_get_end' */
u32 w2c_auto__debug_emscripten_stack_get_end(w2c_auto__debug*);

/* export: '_emscripten_stack_restore' */
void w2c_auto__debug_0x5Femscripten_stack_restore(w2c_auto__debug*, u32);

/* export: 'emscripten_stack_get_current' */
u32 w2c_auto__debug_emscripten_stack_get_current(w2c_auto__debug*);

#ifdef __cplusplus
}
#endif

#endif  /* AUTO_DEBUG_H_GENERATED_ */
